import Link from 'next/link';
import Icon from '@/components/ui/Icon/Icon';
import {
  ETHERSCAN_BASE,
  NETWORK_NAME,
  NFT_ADDRESS,
  UNEST_ADDRESS,
  UNISWAP_BASE,
  etherscanToken,
  openseaCollection,
  uniswapSwap,
} from '@/config/contracts';
import { SOCIAL_LINKS } from '@/config/site';
import { TAGLINE } from '@/config/protocol';
import styles from './Footer.module.css';

export function Footer() {
  const external = [
    ...SOCIAL_LINKS,
    { label: 'UNISWAP', href: uniswapSwap(UNEST_ADDRESS) || UNISWAP_BASE },
    { label: 'ETHERSCAN', href: etherscanToken(UNEST_ADDRESS) ?? ETHERSCAN_BASE },
    ...(openseaCollection(NFT_ADDRESS)
      ? [{ label: 'OPENSEA', href: openseaCollection(NFT_ADDRESS) as string }]
      : []),
  ];

  return (
    <footer className={styles.footer}>
      {/* the barn roofline, in the renderer's Red shell */}
      <div className={styles.roof} aria-hidden="true">
        <svg viewBox="0 0 320 20" preserveAspectRatio="none" shapeRendering="crispEdges">
          {Array.from({ length: 5 }, (_, i) => (
            <rect
              key={i}
              x={0}
              y={i * 4}
              width={320}
              height={4}
              fill={i % 2 === 0 ? '#922b21' : '#a83226'}
              opacity={0.2 + i * 0.16}
            />
          ))}
        </svg>
      </div>

      <div className={styles.inner}>
        <div className={styles.brandCol}>
          <span className={styles.logo}>
            <Icon name="egg" size={16} className={styles.logoMark} />
            UNEST
          </span>
          <p className={styles.tag}>{TAGLINE}</p>
          <p className={styles.blurb}>
            An ERC-20 token whose holders are issued fully on-chain generative pixel chicks. Art,
            traits and metadata are generated by the contract itself.
          </p>
        </div>

        <nav className={styles.col} aria-label="Site">
          <h2 className={styles.colTitle}>SITE</h2>
          <Link href="/" className={styles.link}>
            HOME
          </Link>
          <Link href="/eggs" className={styles.link}>
            YOUR EGGS
          </Link>
          <Link href="/docs" className={styles.link}>
            DOCS
          </Link>
          <Link href="/docs#risk" className={styles.link}>
            RISK
          </Link>
        </nav>

        <nav className={styles.col} aria-label="External">
          <h2 className={styles.colTitle}>OUTSIDE</h2>
          {external.map((l) => (
            <a
              key={l.label}
              className={styles.link}
              href={l.href}
              target="_blank"
              rel="noopener noreferrer"
            >
              {l.label}
              <Icon name="external" size={9} className={styles.linkIcon} />
            </a>
          ))}
        </nav>
      </div>

      {/* fence line */}
      <div className={styles.fence} aria-hidden="true">
        <svg viewBox="0 0 320 14" preserveAspectRatio="none" shapeRendering="crispEdges">
          {Array.from({ length: 32 }, (_, i) => (
            <rect key={i} x={i * 10} y={0} width={3} height={14} fill="#e67e22" />
          ))}
          <rect x={0} y={3} width={320} height={2} fill="#ba4a00" />
          <rect x={0} y={9} width={320} height={2} fill="#ba4a00" />
        </svg>
      </div>

      <div className={styles.bottom}>
        <p className={styles.legal}>{NETWORK_NAME} · UNEST is the token, EGG is the NFT.</p>
        <p className={styles.disclaimer}>
          Not audited. Not risk free. No returns are promised. Rewards depend entirely on swap
          activity and may be nothing at all. Verify every contract yourself before interacting.
        </p>
      </div>
    </footer>
  );
}

export default Footer;
